### ISSUE TITLE
Problema Correr Aplicación

### ISSUE THREAD

**Issue by Manuel-uc** [IIC2513-2018-1/syllabus#16]
Hola profesor:
Tengo un problema al intentar correr la aplicación:
Si intento usar el comando **node index.js**:

> PS C:\Users\Manue\Desktop\Web Proyect\grupo-guerreros-australes-master> node index.js
Unable to connect to the database: { SequelizeConnectionError: read ECONNRESET
    at connection.connect.err (C:\Users\Manue\Desktop\Web Proyect\grupo-guerreros-australes-master\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:128:24)
    at Connection.connectingErrorHandler (C:\Users\Manue\Desktop\Web Proyect\grupo-guerreros-australes-master\node_modules\pg\lib\client.js:123:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.reportStreamError (C:\Users\Manue\Desktop\Web Proyect\grupo-guerreros-australes-master\node_modules\pg\lib\connection.js:71:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'SequelizeConnectionError',
  parent: { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
  original: { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
webpack built 2dbfa1adb30ac1d7f1b5 in 3286ms
i ｢wdm｣: Hash: 2dbfa1adb30ac1d7f1b5
Version: webpack 3.11.0
Time: 3286ms
      Asset     Size  Chunks                    Chunk Names
appReact.js  1.03 MB       0  [emitted]  [big]  appReact
     app.js   299 kB       1  [emitted]  [big]  app
   logo.png  6.93 kB          [emitted]
   [0] ./node_modules/process/browser.js 5.42 kB {0} {1} [built]
   [3] ./node_modules/react/index.js 190 bytes {0} {1} [built]
   [8] ./node_modules/react-hot-loader/index.js 228 bytes {0} [built]
  [10] (webpack)/buildin/module.js 517 bytes {0} {1} [built]
  [12] ./node_modules/react-hot-loader/dist/react-hot-loader.production.min.js 1.31 kB {0} {1} [built]
  [13] ./node_modules/react-hot-loader/dist/react-hot-loader.development.js 45 kB {0} {1} [built]
  [14] ./node_modules/react-hot-loader/patch.js 213 bytes {0} {1} [built]
  [25] ./node_modules/webpack-hot-middleware/client.js?path=/__webpack_hmr&timeout=20000 7.35 kB {0} {1} [built]
  [38] (webpack)/buildin/harmony-module.js 596 bytes {0} [built]
  [43] multi react-hot-loader/patch webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 ./js/index.js 52 bytes {1} [built]
  [44] ./src/assets/js/index.js 82 bytes {1} [built]
  [49] multi react-hot-loader/patch webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 ./js/app.jsx 52 bytes {0} [built]
  [50] ./src/assets/js/app.jsx 846 bytes {0} [built]
  [51] ./node_modules/react-dom/index.js 1.36 kB {0} [built]
  [60] ./src/assets/js/components/App.jsx 859 bytes {0} [built]
    + 46 hidden modules
i ｢wdm｣: Compiled successfully.
>
Si intento usar **yarn start**:
>PS C:\Users\Manue\Desktop\Web Proyect\grupo-guerreros-australes-master> yarn start
yarn run v1.5.1
$ node index.js
Unable to connect to the database: { SequelizeConnectionError: read ECONNRESET
    at connection.connect.err (C:\Users\Manue\Desktop\Web Proyect\grupo-guerreros-australes-master\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:128:24)
    at Connection.connectingErrorHandler (C:\Users\Manue\Desktop\Web Proyect\grupo-guerreros-australes-master\node_modules\pg\lib\client.js:123:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.reportStreamError (C:\Users\Manue\Desktop\Web Proyect\grupo-guerreros-australes-master\node_modules\pg\lib\connection.js:71:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'SequelizeConnectionError',
  parent: { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
  original: { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } }
webpack built 2dbfa1adb30ac1d7f1b5 in 3856ms
i ｢wdm｣: Hash: 2dbfa1adb30ac1d7f1b5
Version: webpack 3.11.0
Time: 3856ms
      Asset     Size  Chunks                    Chunk Names
appReact.js  1.03 MB       0  [emitted]  [big]  appReact
     app.js   299 kB       1  [emitted]  [big]  app
   logo.png  6.93 kB          [emitted]
   [0] ./node_modules/process/browser.js 5.42 kB {0} {1} [built]
   [3] ./node_modules/react/index.js 190 bytes {0} {1} [built]
   [8] ./node_modules/react-hot-loader/index.js 228 bytes {0} [built]
  [10] (webpack)/buildin/module.js 517 bytes {0} {1} [built]
  [12] ./node_modules/react-hot-loader/dist/react-hot-loader.production.min.js 1.31 kB {0} {1} [built]
  [13] ./node_modules/react-hot-loader/dist/react-hot-loader.development.js 45 kB {0} {1} [built]
  [14] ./node_modules/react-hot-loader/patch.js 213 bytes {0} {1} [built]
  [25] ./node_modules/webpack-hot-middleware/client.js?path=/__webpack_hmr&timeout=20000 7.35 kB {0} {1} [built]
  [38] (webpack)/buildin/harmony-module.js 596 bytes {0} [built]
  [43] multi react-hot-loader/patch webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 ./js/index.js 52 bytes {1} [built]
  [44] ./src/assets/js/index.js 82 bytes {1} [built]
  [49] multi react-hot-loader/patch webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 ./js/app.jsx 52 bytes {0} [built]
  [50] ./src/assets/js/app.jsx 846 bytes {0} [built]
  [51] ./node_modules/react-dom/index.js 1.36 kB {0} [built]
  [60] ./src/assets/js/components/App.jsx 859 bytes {0} [built]
    + 46 hidden modules
i ｢wdm｣: Compiled successfully.
>
En ambos casos no me puedo conectar y localhost:3000 no encuentra la página.
Eh peleado varios días, pero no he logrado avanzar mucho. Agradezco cualquier ayuda
Saludos

**Comment by Manuel-uc** [comment]
Gracias profesor.
En postgres esta configurado el usuario y contraseña. 
¿Como puedo saber si estoy pasando correctamente las variables a la app?

**Comment by gpvidal** [comment]
Si corres este comando y te funciona:
```bash
DB_USERNAME=<usuario> DB_PASSWORD=<password> yarn start
```

Entonces estás pasando mal las variables de entorno a la aplicación. Ahora, si sigue sin funcionar, muy probablemente te falta darle permisos al usuario que creaste a la base de datos.

**Comment by Manuel-uc** [comment]
Muchas gracias! :)
