### ISSUE TITLE
Duda variable de entorno

### ISSUE THREAD

**Issue by roy350** [IIC2513-2018-1/syllabus#70]
Una duda con my university, en la parte de la api, para auth se tiene en un momento para la identificación la siguiente linea ```process.env.JWT_SECRET``` que comprendo es una variable de entorno, pero esta que debe contener? estoy pegado en un error relacionado a esto, supongo.  Que al ejecutar un post, con los respectivos values para el user me da el siguiente error

``` 
Error: secretOrPrivateKey must have a value
      at Object.module.exports [as sign] (/Users/Roy350/grupo-nodekoahacer/node_modules/jsonwebtoken/sign.js:101:20)
      at Promise (/Users/Roy350/grupo-nodekoahacer/src/routes/api/auth.js:11:20)
      at new Promise (<anonymous>)
      at router.post (/Users/Roy350/grupo-nodekoahacer/src/routes/api/auth.js:10:25)
      at <anonymous>
```

Si tiene alguna idea se lo agradeceria mucho!

**Comment by nacosta-cl** [comment]
Rod yo le puse cq cosa, como 

`DB_USERNAME=miusername DB_PASSWORD=miclave JWT_SECRET=meow node_modules/nodemon/bin/nodemon.js`

**Comment by gpvidal** [comment]
Hola @roy350 !
Tal como dice @nacosta-cl , `JWT_SECRET` es un texto :wink: 

Saludos,
